# Generated by Django 5.2.6 on 2025-09-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amasonsito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
