# Generated by Django 5.2.6 on 2025-09-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amasonsito', '0002_producto_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
